"""Add is_custom to Reward

Revision ID: 72597b7e67e8
Revises: c073e4706313
Create Date: 2025-12-04 19:03:16.492416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72597b7e67e8'
down_revision: Union[str, Sequence[str], None] = 'c073e4706313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('is_custom', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'is_custom')
    # ### end Alembic commands ###
